#define BUILD                       "20181112"
#define PACKAGE_NAME                "libjpeg-turbo"
#define VERSION                     "2.0.1"
#define LIBJPEG_TURBO_VERSION       "2.0.1"
#define JPEG_LIB_VERSION            62
#define C_ARITH_CODING_SUPPORTED    1
#define D_ARITH_CODING_SUPPORTED    1
#define BITS_IN_JSAMPLE             8
#define HAVE_DLFCN_H                1
#define HAVE_INTTYPES_H             1
#define HAVE_LOCALE_H               1
#define HAVE_MEMCPY                 1
#define HAVE_MEMORY_H               1
#define HAVE_MEMSET                 1
#define HAVE_STDDEF_H               1
#define HAVE_STDINT_H               1
#define HAVE_STDLIB_H               1
#define HAVE_STRINGS_H              1
#define HAVE_STRING_H               1
#define HAVE_SYS_STAT_H             1
#define HAVE_SYS_TYPES_H            1
#define HAVE_UNISTD_H               1
#define HAVE_UNSIGNED_CHAR          1
#define HAVE_UNSIGNED_SHORT         1
#define INLINE                      "inline __attribute__((always_inline))"
#define MEM_SRCDST_SUPPORTED        1
#define NEED_SYS_TYPES_H            1
#define STDC_HEADERS                1
#define WITH_SIMD                   1
